
drop table pizzas if exists;

create table pizzas (
	id_pizza integer primary key generated by default as identity(start with 10),
	name varchar(15) not null,
	price numeric(15,2) not null
);

-- ================================================


drop sequence seq_exp if exists;
create sequence seq_exp start with 100;

drop table exp if exists;

create table exp (
	id_ens smallint, 
	num_exp integer,
	fase varchar(20)
);
alter table exp add constraint pk_expid primary key (id_ens, num_exp);
