package org.homs.lechuga.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class EntityModel<E> {

    final Class<E> entityClass;
    final String tableName;

    final List<EntityPropertyModel> idProperties;
    final List<EntityPropertyModel> nonIdProperties;
    final List<EntityPropertyModel> allProperties;

    final Map<String, EntityPropertyModel> propertyNamesMap;
    final List<EntityPropertyModel> autogeneratedProperties;

    public EntityModel(Class<E> entityClass, String tableName, List<EntityPropertyModel> idProperties, List<EntityPropertyModel> nonIdProperties) {
        this.entityClass = entityClass;
        this.tableName = tableName;
        this.idProperties = idProperties;
        this.nonIdProperties = nonIdProperties;

        this.allProperties = new ArrayList<>();
        this.allProperties.addAll(idProperties);
        this.allProperties.addAll(nonIdProperties);

        this.propertyNamesMap = allProperties.stream()
                .collect(Collectors.toMap(EntityPropertyModel::getPropertiesPath, p -> p));

        this.autogeneratedProperties = Stream.concat(idProperties.stream(), nonIdProperties.stream())
                .filter(p -> p.getGenerator() != null)
                .collect(Collectors.toList());
    }

    public Class<E> getEntityClass() {
        return entityClass;
    }

    public String getTableName() {
        return tableName;
    }

    public List<EntityPropertyModel> getIdProperties() {
        return idProperties;
    }

    public List<EntityPropertyModel> getNonIdProperties() {
        return nonIdProperties;
    }

    public List<EntityPropertyModel> getAllProperties() {
        return allProperties;
    }

    public Map<String, EntityPropertyModel> getPropertyNamesMap() {
        return propertyNamesMap;
    }

    public List<EntityPropertyModel> getAutogeneratedProperties() {
        return autogeneratedProperties;
    }

    @Override
    public String toString() {
        return "Entity{" +
                "entityClass=" + entityClass +
                ", tableName='" + tableName + '\'' +
                ", properties=" + allProperties +
                '}';
    }
}